name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './gui_tensor_expressions/package-lock.json'

      - name: Clean install
        working-directory: ./gui_tensor_expressions
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm install
          npm install @babel/plugin-proposal-private-property-in-object@7.21.11

      - name: Run tests
        working-directory: ./gui_tensor_expressions
        run: |
          CI=true npm test -- --coverage --passWithNoTests
          

      - name: Build
        working-directory: ./gui_tensor_expressions
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gui_tensor_expressions/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4